# Form implementation generated from reading ui file 'AdminWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(338, 278)
        self.centralwidget = QtWidgets.QWidget(parent=AdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addUsr_btn = QtWidgets.QPushButton(parent=self.frame)
        self.addUsr_btn.setObjectName("addUsr_btn")
        self.verticalLayout.addWidget(self.addUsr_btn)
        self.editUsr_btn = QtWidgets.QPushButton(parent=self.frame)
        self.editUsr_btn.setObjectName("editUsr_btn")
        self.verticalLayout.addWidget(self.editUsr_btn)
        self.deleteUsr_btn = QtWidgets.QPushButton(parent=self.frame)
        self.deleteUsr_btn.setObjectName("deleteUsr_btn")
        self.verticalLayout.addWidget(self.deleteUsr_btn)
        self.verticalLayout_2.addWidget(self.frame)
        AdminWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=AdminWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 338, 22))
        self.menubar.setObjectName("menubar")
        AdminWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=AdminWindow)
        self.statusbar.setObjectName("statusbar")
        AdminWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AdminWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "Administration"))
        self.addUsr_btn.setText(_translate("AdminWindow", "Add new user"))
        self.editUsr_btn.setText(_translate("AdminWindow", "Edit user"))
        self.deleteUsr_btn.setText(_translate("AdminWindow", "Delete user"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminWindow()
    ui.setupUi(AdminWindow)
    AdminWindow.show()
    sys.exit(app.exec())
