# Form implementation generated from reading ui file 'DeleteUsrWIndow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeleteUsrWindow(object):
    def setupUi(self, DeleteUsrWindow):
        DeleteUsrWindow.setObjectName("DeleteUsrWindow")
        DeleteUsrWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=DeleteUsrWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.usr_twidget = QtWidgets.QTableWidget(parent=self.frame)
        self.usr_twidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.usr_twidget.setObjectName("usr_twidget")
        self.usr_twidget.setColumnCount(0)
        self.usr_twidget.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.usr_twidget)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.delete_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.delete_btn.setObjectName("delete_btn")
        self.verticalLayout.addWidget(self.delete_btn)
        self.close_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.close_btn.setObjectName("close_btn")
        self.verticalLayout.addWidget(self.close_btn)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        DeleteUsrWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=DeleteUsrWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        DeleteUsrWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=DeleteUsrWindow)
        self.statusbar.setObjectName("statusbar")
        DeleteUsrWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DeleteUsrWindow)
        QtCore.QMetaObject.connectSlotsByName(DeleteUsrWindow)

    def retranslateUi(self, DeleteUsrWindow):
        _translate = QtCore.QCoreApplication.translate
        DeleteUsrWindow.setWindowTitle(_translate("DeleteUsrWindow", "Deletion"))
        self.delete_btn.setText(_translate("DeleteUsrWindow", "Delete selected"))
        self.close_btn.setText(_translate("DeleteUsrWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteUsrWindow = QtWidgets.QMainWindow()
    ui = Ui_DeleteUsrWindow()
    ui.setupUi(DeleteUsrWindow)
    DeleteUsrWindow.show()
    sys.exit(app.exec())
