# Form implementation generated from reading ui file 'GuestSelectWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SelectGuestWIndow(object):
    def setupUi(self, SelectGuestWIndow):
        SelectGuestWIndow.setObjectName("SelectGuestWIndow")
        SelectGuestWIndow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=SelectGuestWIndow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_twidget = QtWidgets.QTableWidget(parent=self.frame)
        self.select_twidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.select_twidget.setObjectName("select_twidget")
        self.select_twidget.setColumnCount(0)
        self.select_twidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.select_twidget)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.resresh_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.resresh_btn.setObjectName("resresh_btn")
        self.verticalLayout.addWidget(self.resresh_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.selectEdit_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.selectEdit_btn.setObjectName("selectEdit_btn")
        self.verticalLayout.addWidget(self.selectEdit_btn)
        self.select_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.select_btn.setObjectName("select_btn")
        self.verticalLayout.addWidget(self.select_btn)
        self.selectEditRmate_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.selectEditRmate_btn.setObjectName("selectEditRmate_btn")
        self.verticalLayout.addWidget(self.selectEditRmate_btn)
        self.selectRmate_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.selectRmate_btn.setObjectName("selectRmate_btn")
        self.verticalLayout.addWidget(self.selectRmate_btn)
        self.addEditGuest_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.addEditGuest_btn.setObjectName("addEditGuest_btn")
        self.verticalLayout.addWidget(self.addEditGuest_btn)
        self.addGuest_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.addGuest_btn.setObjectName("addGuest_btn")
        self.verticalLayout.addWidget(self.addGuest_btn)
        self.close_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.close_btn.setObjectName("close_btn")
        self.verticalLayout.addWidget(self.close_btn)
        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout_2.addWidget(self.frame)
        SelectGuestWIndow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SelectGuestWIndow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        SelectGuestWIndow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SelectGuestWIndow)
        self.statusbar.setObjectName("statusbar")
        SelectGuestWIndow.setStatusBar(self.statusbar)

        self.retranslateUi(SelectGuestWIndow)
        QtCore.QMetaObject.connectSlotsByName(SelectGuestWIndow)

    def retranslateUi(self, SelectGuestWIndow):
        _translate = QtCore.QCoreApplication.translate
        SelectGuestWIndow.setWindowTitle(_translate("SelectGuestWIndow", "Guest selection"))
        self.resresh_btn.setText(_translate("SelectGuestWIndow", "Refresh"))
        self.selectEdit_btn.setText(_translate("SelectGuestWIndow", "Select"))
        self.select_btn.setText(_translate("SelectGuestWIndow", "Select"))
        self.selectEditRmate_btn.setText(_translate("SelectGuestWIndow", "Select as roommate"))
        self.selectRmate_btn.setText(_translate("SelectGuestWIndow", "Select as roommate"))
        self.addEditGuest_btn.setText(_translate("SelectGuestWIndow", "Add new guest"))
        self.addGuest_btn.setText(_translate("SelectGuestWIndow", "Add new guest"))
        self.close_btn.setText(_translate("SelectGuestWIndow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelectGuestWIndow = QtWidgets.QMainWindow()
    ui = Ui_SelectGuestWIndow()
    ui.setupUi(SelectGuestWIndow)
    SelectGuestWIndow.show()
    sys.exit(app.exec())
