# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(313, 195)
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pswd_lbl = QtWidgets.QLabel(parent=self.frame)
        self.pswd_lbl.setObjectName("pswd_lbl")
        self.gridLayout_2.addWidget(self.pswd_lbl, 2, 0, 1, 1)
        self.usr_leddit = QtWidgets.QLineEdit(parent=self.frame)
        self.usr_leddit.setObjectName("usr_leddit")
        self.gridLayout_2.addWidget(self.usr_leddit, 1, 1, 1, 1)
        self.usr_lbl = QtWidgets.QLabel(parent=self.frame)
        self.usr_lbl.setObjectName("usr_lbl")
        self.gridLayout_2.addWidget(self.usr_lbl, 1, 0, 1, 1)
        self.pswd_leddit = QtWidgets.QLineEdit(parent=self.frame)
        self.pswd_leddit.setInputMask("")
        self.pswd_leddit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pswd_leddit.setCursorPosition(6)
        self.pswd_leddit.setObjectName("pswd_leddit")
        self.gridLayout_2.addWidget(self.pswd_leddit, 2, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.welcome_lbl = QtWidgets.QLabel(parent=self.frame_3)
        self.welcome_lbl.setObjectName("welcome_lbl")
        self.horizontalLayout_2.addWidget(self.welcome_lbl)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(652, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.submit_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.submit_btn.setObjectName("submit_btn")
        self.horizontalLayout.addWidget(self.submit_btn)
        self.verticalLayout.addWidget(self.frame_2)
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 313, 22))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Welcome"))
        self.pswd_lbl.setText(_translate("LoginWindow", "Password"))
        self.usr_leddit.setText(_translate("LoginWindow", "hotel_admin"))
        self.usr_lbl.setText(_translate("LoginWindow", "User name"))
        self.pswd_leddit.setText(_translate("LoginWindow", "batman"))
        self.welcome_lbl.setText(_translate("LoginWindow", "Welcome to the Hotelier decktop app! Please log in."))
        self.submit_btn.setText(_translate("LoginWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec())
