# Form implementation generated from reading ui file 'PopUpWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PopUp(object):
    def setupUi(self, PopUp):
        PopUp.setObjectName("PopUp")
        PopUp.resize(166, 166)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(PopUp)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(parent=PopUp)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.popup_txt = QtWidgets.QLabel(parent=self.frame)
        self.popup_txt.setObjectName("popup_txt")
        self.verticalLayout.addWidget(self.popup_txt)
        self.horizontalLayout_2.addWidget(self.frame)

        self.retranslateUi(PopUp)
        QtCore.QMetaObject.connectSlotsByName(PopUp)

    def retranslateUi(self, PopUp):
        _translate = QtCore.QCoreApplication.translate
        PopUp.setWindowTitle(_translate("PopUp", "PopUp"))
        self.popup_txt.setText(_translate("PopUp", "DefaultTxt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PopUp = QtWidgets.QWidget()
    ui = Ui_PopUp()
    ui.setupUi(PopUp)
    PopUp.show()
    sys.exit(app.exec())
