# Form implementation generated from reading ui file 'RateWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RateWindow(object):
    def setupUi(self, RateWindow):
        RateWindow.setObjectName("RateWindow")
        RateWindow.resize(877, 650)
        self.centralwidget = QtWidgets.QWidget(parent=RateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rate_tWidget = QtWidgets.QTableWidget(parent=self.frame)
        self.rate_tWidget.setObjectName("rate_tWidget")
        self.rate_tWidget.setColumnCount(0)
        self.rate_tWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.rate_tWidget)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.saveEdit_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.saveEdit_btn.setObjectName("saveEdit_btn")
        self.verticalLayout_2.addWidget(self.saveEdit_btn)
        self.save_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout_2.addWidget(self.save_btn)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        RateWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=RateWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 22))
        self.menubar.setObjectName("menubar")
        RateWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=RateWindow)
        self.statusbar.setObjectName("statusbar")
        RateWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RateWindow)
        QtCore.QMetaObject.connectSlotsByName(RateWindow)

    def retranslateUi(self, RateWindow):
        _translate = QtCore.QCoreApplication.translate
        RateWindow.setWindowTitle(_translate("RateWindow", "Rates"))
        self.saveEdit_btn.setText(_translate("RateWindow", "Save"))
        self.save_btn.setText(_translate("RateWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RateWindow = QtWidgets.QMainWindow()
    ui = Ui_RateWindow()
    ui.setupUi(RateWindow)
    RateWindow.show()
    sys.exit(app.exec())
