# Form implementation generated from reading ui file 'ReportWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ReportWindow(object):
    def setupUi(self, ReportWindow):
        ReportWindow.setObjectName("ReportWindow")
        ReportWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=ReportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reports_twidget = QtWidgets.QTableWidget(parent=self.frame)
        self.reports_twidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.reports_twidget.setObjectName("reports_twidget")
        self.reports_twidget.setColumnCount(0)
        self.reports_twidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.reports_twidget)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.report_daddit = QtWidgets.QDateEdit(parent=self.frame_2)
        self.report_daddit.setCalendarPopup(True)
        self.report_daddit.setObjectName("report_daddit")
        self.verticalLayout.addWidget(self.report_daddit)
        self.arrReport_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.arrReport_btn.setObjectName("arrReport_btn")
        self.verticalLayout.addWidget(self.arrReport_btn)
        self.depReport_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.depReport_btn.setObjectName("depReport_btn")
        self.verticalLayout.addWidget(self.depReport_btn)
        self.incCanc_chbx = QtWidgets.QCheckBox(parent=self.frame_2)
        self.incCanc_chbx.setObjectName("incCanc_chbx")
        self.verticalLayout.addWidget(self.incCanc_chbx)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.save_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout.addWidget(self.save_btn)
        self.canc_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.canc_btn.setObjectName("canc_btn")
        self.verticalLayout.addWidget(self.canc_btn)
        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout_2.addWidget(self.frame)
        ReportWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ReportWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        ReportWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ReportWindow)
        self.statusbar.setObjectName("statusbar")
        ReportWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ReportWindow)
        QtCore.QMetaObject.connectSlotsByName(ReportWindow)

    def retranslateUi(self, ReportWindow):
        _translate = QtCore.QCoreApplication.translate
        ReportWindow.setWindowTitle(_translate("ReportWindow", "Generate report"))
        self.report_daddit.setDisplayFormat(_translate("ReportWindow", "yyyy-MM-dd"))
        self.arrReport_btn.setText(_translate("ReportWindow", "Arrivals report"))
        self.depReport_btn.setText(_translate("ReportWindow", "Departures report"))
        self.incCanc_chbx.setText(_translate("ReportWindow", "Include cancelled"))
        self.save_btn.setText(_translate("ReportWindow", "Save to file"))
        self.canc_btn.setText(_translate("ReportWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReportWindow = QtWidgets.QMainWindow()
    ui = Ui_ReportWindow()
    ui.setupUi(ReportWindow)
    ReportWindow.show()
    sys.exit(app.exec())
