# Form implementation generated from reading ui file 'ReservationDetailsWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DetailsMAinWindow(object):
    def setupUi(self, DetailsMAinWindow):
        DetailsMAinWindow.setObjectName("DetailsMAinWindow")
        DetailsMAinWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=DetailsMAinWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.details_twidget = QtWidgets.QTableWidget(parent=self.frame)
        self.details_twidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.details_twidget.setObjectName("details_twidget")
        self.details_twidget.setColumnCount(0)
        self.details_twidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.details_twidget)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.close_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.close_btn.setObjectName("close_btn")
        self.verticalLayout.addWidget(self.close_btn)
        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout_2.addWidget(self.frame)
        DetailsMAinWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=DetailsMAinWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        DetailsMAinWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=DetailsMAinWindow)
        self.statusbar.setObjectName("statusbar")
        DetailsMAinWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DetailsMAinWindow)
        QtCore.QMetaObject.connectSlotsByName(DetailsMAinWindow)

    def retranslateUi(self, DetailsMAinWindow):
        _translate = QtCore.QCoreApplication.translate
        DetailsMAinWindow.setWindowTitle(_translate("DetailsMAinWindow", "Reservation details"))
        self.close_btn.setText(_translate("DetailsMAinWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DetailsMAinWindow = QtWidgets.QMainWindow()
    ui = Ui_DetailsMAinWindow()
    ui.setupUi(DetailsMAinWindow)
    DetailsMAinWindow.show()
    sys.exit(app.exec())
