# Form implementation generated from reading ui file 'ReservationEditRateWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ResEditRateWindow(object):
    def setupUi(self, ResEditRateWindow):
        ResEditRateWindow.setObjectName("ResEditRateWindow")
        ResEditRateWindow.resize(877, 650)
        self.centralwidget = QtWidgets.QWidget(parent=ResEditRateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editRate_tWidget = QtWidgets.QTableWidget(parent=self.frame)
        self.editRate_tWidget.setObjectName("editRate_tWidget")
        self.editRate_tWidget.setColumnCount(0)
        self.editRate_tWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.editRate_tWidget)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.save_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout_2.addWidget(self.save_btn)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        ResEditRateWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ResEditRateWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 22))
        self.menubar.setObjectName("menubar")
        ResEditRateWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ResEditRateWindow)
        self.statusbar.setObjectName("statusbar")
        ResEditRateWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ResEditRateWindow)
        QtCore.QMetaObject.connectSlotsByName(ResEditRateWindow)

    def retranslateUi(self, ResEditRateWindow):
        _translate = QtCore.QCoreApplication.translate
        ResEditRateWindow.setWindowTitle(_translate("ResEditRateWindow", "Rates"))
        self.save_btn.setText(_translate("ResEditRateWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResEditRateWindow = QtWidgets.QMainWindow()
    ui = Ui_ResEditRateWindow()
    ui.setupUi(ResEditRateWindow)
    ResEditRateWindow.show()
    sys.exit(app.exec())
